from datetime import datetime
from sqlalchemy import Boolean, Column, DateTime, Float, Integer, String, Text
from database import Base


class LandRecord(Base):
    __tablename__ = "land_records"

    id = Column(Integer, primary_key=True, index=True)

    # Unique identifier generated by system (e.g., LR-2026-8253DB32)
    record_id = Column(
        String(100),
        unique=True,
        index=True,
        nullable=False
    )

    # Document number extracted from deed or generated (e.g., DOC-2026-9812)
    document_number = Column(
        String(100),
        index=True,
        nullable=True
    )

    owner_name = Column(String(255), index=True, nullable=True)
    father_name = Column(String(255), nullable=True)

    owner_mobile = Column(String(50), nullable=True)
    owner_aadhar = Column(String(50), nullable=True)
    owner_pan = Column(String(50), nullable=True)

    district = Column(String(100), index=True, nullable=True)
    village = Column(String(100), index=True, nullable=True)

    survey_number = Column(String(100), index=True, nullable=True)

    land_area = Column(String(100), nullable=True)
    land_type = Column(String(100), nullable=True)

    registration_date = Column(String(100), nullable=True)

    # Status: 'Verified', 'Review', 'Pending', 'Rejected'
    status = Column(
        String(50),
        default="Pending",
        index=True
    )

    risk_level = Column(String(50), default="UNKNOWN")
    risk_score = Column(Float, default=0.0)
    confidence_score = Column(Float, default=0.0)

    # SHA-256 digital document integrity hash for tamper detection (SIH Hackathon)
    document_hash = Column(String(64), nullable=True)
    is_tampered = Column(Boolean, default=False)

    # Missing/Incomplete fields JSON list
    missing_fields = Column(Text, nullable=True)

    # Audit Trail JSON list of changes and verifier actions
    audit_trail = Column(Text, nullable=True)
    is_manually_edited = Column(Boolean, default=False)

    raw_text = Column(Text, nullable=True)
    extracted_fields = Column(Text, nullable=True)  # JSON-encoded
    validation_results = Column(Text, nullable=True)  # JSON-encoded

    source_file = Column(String(500), nullable=True)

    verified_by = Column(String(100), nullable=True)
    verified_at = Column(DateTime, nullable=True)

    created_at = Column(
        DateTime,
        default=datetime.utcnow
    )

    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow
    )